### PR TITLE
Added rkJointCopyPrp and joint_clone_test, and modified rkJointClone.

### PR DESCRIPTION
**Pull request by n-wakisaka**
This PR resolves the issue #26 , where `rkJointClone` was not copying the properties of Joint.

Here are the implemented changes:

* Added a new function `rkJointCopyPrp` that copies the Joint properties.
* Added `joint_clone_test.c` for testing and validation.
* Modified the `rkJointClone` function.

### CODE REVIEW

**Comment by zhidao** [comment]
@n-wakisaka 
No problem to add the function to copy the joint properties as a member of rkJointCom. I imagine that it can be implemented in a more sophisticated way such as:
```C
#define ROKI_DEF_JOINT_COPY_PRP_METHOD(type) \
void *_rkJoint##type##CopyPrp(void *prp1, void *prp2){\
  memcpy( prp2, prp1, sizeof(rkJoint##type##Prp) );\
}
...
ROKI_DEF_JOINT_COPY_PRP_METHOD( Revol )
```
One thing that might be a problem is that some of the joint classes have rkMotor as a member of the properties. It might be nicer to move it out of the properties and modify rkJoint to directly have rkMotor in it.

Concerning with the above, I noticed that rkJoint*Prp has an instance of rkMotor, which rkChain has an array of rkMotor (rkMotorArray). I supposed each joint had a pointer to one of the element of the array or the null, and so, I'm confused.

**Comment by zhidao** [comment]
I had to add that it might also be better to separate the joint properties to rkJoint*Prp and rkJoint*State.

**Comment by n-wakisaka** [comment]
Thank you for your response!

Like you, I initially considered using memcpy for the copy process. However, I was concerned that there might be issues with a proper deep copy for elements that require it. I agree that the copying of rkMotor might not be working.

I think it's a good idea to have rkJoint directly contain rkMotor. If we proceed in this manner, it will probably be necessary to revise the functions related to rkMotor within rkJointCom. It might suffice to just include rkMotor as an argument.

The array of rkMotor in rkChain represents a sort of 'catalog value'. Each rkMotor within rkJoint was designed to initially copy data from these catalog values, allowing for parts of the data to be overwritten. Hence, the current structure.

I agree with the idea of separating the joint properties into rkJointPrp and rkJointState.

**Comment by zhidao** [comment]
@n-wakisaka Sorry for the late response. I'm updating the branch in my local repository.
Basically, I intend to separate properties and state variables of `rkJoint` as I told you above. For a prior arrangement, I modified specifications of member functions of `rkJointCom` to accept a pointer to the original instance of `rkJoint` rather than that to its property.
I pushed this revision but continue to modify it. JFYI.

**Comment by zhidao** [comment]
@n-wakisaka I separated joint states from joint properties. If I take the `rkMotor` instance directly in `rkJoint` out of `rkJoint*Prp`, I think I can apply simple `memcpy()` to both `rkJointCopyState()` and `rkJointCopyPrp()`.
I'm a bit wondering if `rkJointCylin` and `rkJointHooke` really need a motor. What do you think?

**Comment by zhidao** [comment]
@n-wakisaka I'm considering about the specification of `rkMotor`.
As far as I understand, the reason why each joint has to have an instance of `rkMotor` in its properties is because it has two types of parameters, namely, type-specific values such as a motor constant and a rotor inertia, and instance-specific values such as input voltage.
So, if we split the latter values out of the properties just as well as `rkJoint*Prp`, will it be possible to simply refer the "catalog" of `rkMotorArray` for the former values? If this is correct, we can reimplement `rkMotor` as:
```C
  typedef struct{
    Z_NAMED_CLASS;
    void *state; /* instance-specific values */
    rkMotorPrp *prp; /* a pointer to a set of type-specific values in catalog */
    rkMotorCom *com;
  } rkMotor;
```
with a modification of `rkMotorArray` to `rkMotorPrpArray`.
Or, could it happen that you want to adjust the type-specific values to individual joints?

**Comment by n-wakisaka** [comment]
@zhidao 
> If I take the rkMotor instance directly in rkJoint out of rkJoint*Prp, 

I think it's good!

> I'm a bit wondering if rkJointCylin and rkJointHooke really need a motor. What do you think?

I believe they are not necessary for `rkJointCylin` and `rkJointHooke`, unless there is a motor that interferes with other axes, such as a spherical motor. Since I have never seen such a motor, I think it's fine to not have a motor for `rkJointCylin` and `rkJointHooke`. If there is no axis interference, it can be achieved by combining `rkJointRevol` and `rkJointPrism`.

**Comment by n-wakisaka** [comment]
@zhidao 
> if we split the latter values out of the properties just as well as rkJoint*Prp, will it be possible to simply refer the "catalog" of rkMotorArray for the former values?
Or, could it happen that you want to adjust the type-specific values to individual joints?

I think it's good to split the state and properties so that it becomes easier to distinguish between changing and non-changing values.

When considering its use in a simple simulation, I believe it would be sufficient to only refer to the catalog values.
While I initially thought that it would be better to have the ability to individually adjust type-specific values when comparing simulation results with actual experimental results for calibration purposes, if individual adjustments are considered, the catalog values may no longer have much meaning. In that case, it might also be a good idea to create each `rkMotorPrp` and refer to them all using the `rkMotorPrpArray`.

**Comment by zhidao** [comment]
@n-wakisaka Thx for your response.

In terms of `rkJointCylin/Hooke`, my concern is that only 1-DOF actuators can be defined as subclasses of our `rkMotor`, and so, it doesn't make sense to equip those joints with a single 1-DOF motor. Though some might think about assigning two instances of `rkMotor` for those joints, as you recognize, it should be replaced with two revolute/prismatic joints. I'm happy that we agree to remove it.

The same discussion applies to `rkMotor` in `rkJointSpher`. I know why you assign it because we know there are some sorts of spherical motors in reality. But, as I explained above, our `rkMotor` cannot define those kinds. Possible option might be (1) to redefine `rkMotor` so as to be able to define multi-DOF motors, or (2) to remove `rkMotor` from `rkJointSpher`. What do you think?

**Comment by n-wakisaka** [comment]
@zhidao 

rkMotor was designed to allow the definition of motors with mult-DOF, taking inspiration from rkJoint. Currently, the library provides only 1-DOF motors, but I believe users can implement spherical motors if needed. Therefore, I think it's fine to have rkMotor in rkJointSphere as well.

**Comment by zhidao** [comment]
@n-wakisaka 
Though it is possible in theory to define subclasses of `rkMotor` with multiple DOFs, there has to be a mean to guarantee that the motor has the same DOF with the joint which it is mounted on. An easy idea is to add `dof` member to `rkMotorCom` as well as `rkJointCom` and compare them to check if they match.
To be honest, I hesitate to do it because I personally don't think that the spherical motor is *too special*. I don't think it practical, and I don't come up with any other types of motors with multiple DOFs.
What is your opinion?

**Comment by n-wakisaka** [comment]
@zhidao 
I agree that it may not be practically necessary. Moreover, since the implementation of the spherical joint in the ABI method is incomplete, defining a spherical motor is currently not usable. However, I believe allowing the definition of multi-DOF motors could increase user flexibility. There might be a demand to define specialized motors for animation creation that appears to incorporate certain physical phenomena, rather than modeling real motors. I understand that this might not align with the envisioned use case of the RoKi library. 

If considering multi-DOF motors, I agree that a DOF check would be necessary for safety. Alternatively, it might be a good idea to define joint types corresponding to each rkMotor, since it's unlikely to set the same rkMotor for multiple types of joints.

**Comment by zhidao** [comment]
> There might be a demand to define specialized motors for animation creation that appears to incorporate certain physical phenomena, rather than modeling real motors.

Sounds interesting.

I'll take an action for this.

**Comment by zhidao** [comment]
@n-wakisaka 
At last I finished revising rkMotor and rkJoint. Major points of the revision are

 - rkMotorSpec is defined, and rkMotor is newly defined. The former has properties (prp) and methods (rkMotorCom), while the latter has states (state) and a pointer to rkMotorSpec (spec).
 - rkMotorCom is modified to have methods for both rkMotorSpec (_alloc_prp, _copy_prp) and rkMotor (_alloc_state, _copy_state).
 - APIs of methods of rkMotorCom are modified to accept a pointer to rkMotorSpec/rkMotor as an argument rather than a void pointer for prp.
 - rkJoint is modified to have a pointer to rkMotor, which is dynamically allocated only when the joint has an actuation. Also, members for state are split from prp to state.
 - APIs of methods of rkJointCom are modified to accept a pointer to rkJoint rather than a void pointer for prp.
 - rkChain is modified to have an array of rkMotorSpec (rkMotorSpecArray) instead of that of rkMotor (rkMotorArray). rkMotorArray is abolished. Individual instances of rkMotor in rkJoint point an element of the array.

and, minor revisions include

 - rkJointGetMotor is abolished since a pointer to rkMotor of rkJoint can be directly referred as rkJointMotor.
 - rkJoint/MotoQueryAssign are renamed to rkJoint/MotorAssignByStr.
 - rkJointCopyPrp/State are simplified with memcpy.
 - rkJoint/MotorSize are renamed to rkJoint/MotorDOF.
 - A member link of rkChain is renamed to linkarray.
 - Some methods for rkLinkArray is added.

Could you check the revisions? I'll merge the branch to the main branch if they have no problems.

**Comment by n-wakisaka** [comment]
@zhidao 
Thanks for the update! 
I haven't been able to run the revisions yet, but from what I've seen of the code it looks good to me!

**Pull request merged**
