### PR TITLE
export rkIKInit and rkIKLoad

### PR DESCRIPTION
**Pull request by categoryik**
When we use c++ language, we create IK(inverse kinematics) solver and load model at different location than creation.
So, I have divided `rkIKCreate` into two steps `rkIKInit` and `rkIKLoad`, and export them.

I am struggling with how to check the IK solver is initialized or not when rkIKLoad is called.
If someone have good ideas, I would be happy to have any suggestions.

### CODE REVIEW

**Comment by zhidao** [comment]
I don't fully understand in which situation the initialization of a rkIK instance and the model loading are separately called. Would you present some example cases?
In my idea, the rkIK instance should be necessarily initialized before loading a model. It is permitted to switch a model to a new one without initialization only when its structure is completely identical with the old one.

**Comment by categoryik** [comment]
In the case of that the model used in IKSolver is not determined at the object creation, IK solver class will be like below class, I think. (that is written in c++, but this may not pass compiler.)
```c++
class IKSolver{
    public:
        IKSolver();
        ~IKSolver();
        loadModel();
    private:
        rkIK ik_;    
};
```
If rkIKInit() is not exported, they will be implemented like
```c++
IKSolver:IKSolver(){
    // do nothing    
}

IKSolver:~IKSolver(){
    rkIKDestroy(&ik_);
}

IKSolver::loadModel(const std::string& path){
    rkIKCreate(&ik_, path);
}
```
In this implementation, if the loadModel() function have not called until object destruction, an error occur because not initialized rkIK will destroy at destructor.
Ther purpose of this PR is to make following implementation available by exporting rkIKInit() which is defined as `_rkIKInit()` now and rkIKLoad()  which is new function.

```c++
IKSolver:IKSolver(){
    rkIKInit();
}

IKSolver:~IKSolver(){
    rkIKDestroy(&ik_);
}

IKSolver::loadModel(const std::string& path){
    rkIKLoad(&ik_, path);
}
```

**Comment by zhidao** [comment]
I think the following idea works:
```
IKSolver:IKSolver(){
    rkIKInit(&ik_);
}

IKSolver:~IKSolver(){
    rkIKDestroy(&ik_);
}

IKSolver::loadModel(const std::string& path){
    rkIKCreate(&ik_, path);
}
```
In order to do it, rkIKInit() has to be exported, while rkIKLoad() is not. What do you think?

**Comment by categoryik** [comment]
Thank you. That will be fine with me.

**Pull request merged**
